---
# vars file for epfl.infoscience-exports
app_name: "infoscience-exports"
svc_name: "web-service"
route_name: "{{ app_name }}"
cron_job_name: "{{ app_name }}-clear-sessions"
secret_name: "infoscience-exports.secrets"
config_maps_name: "infoscience-exports-config"
cname: "infoscience-exports.epfl.ch"
deploy_name: "django-app"
volume_name_logs: "pvc-export-logs"
volume_name_staticfiles: "{{ app_name }}-staticfiles"

quay_host: "quay-its.epfl.ch"
quay_organisation_name: svc0089
quay_repo: "{{ quay_host }}/{{ quay_organisation_name }}"

_quay_push_pull_credential: "{{ lookup('file', '/keybase/team/epfl_idevfsd/infoscience-exports/QUAY_BOT_ACCOUNT') }}"

quay_push_pull_config:
  auths:
    "quay-its.epfl.ch":
      "auth": "{{ _quay_push_pull_credential | b64encode }}"
