- name: infoscience-exports clearsesssions cron job
  tags:
    - cron-job
  openshift:
    state: latest
    resource: CronJob
    name: "{{ cron_job_name }}"
    namespace: "{{ openshift_namespace }}"
    content: |
      apiVersion: batch/v1beta1
      kind: CronJob
      metadata:
        name: "{{ cron_job_name }}"
      spec:
        schedule: "0 3 * * *"
        concurrencyPolicy: "Replace"
        jobTemplate:
          spec:
            template:
              metadata:
                labels:
                  app: "{{ app_name }}"
                  author: jdelasoie
                  team: idev-fsd
              spec:
                containers:
                  - name: "{{ cron_job_name }}"
                    image: "{{ openshift_local_images_base }}"
                    command: ["/usr/local/bin/python", "/usr/src/app/infoscience_exports/manage.py", "clearsessions"]
                    volumeMounts:
                      - mountPath: /var/log/django
                        name: "volume-{{ volume_name_logs }}"
                    envFrom:
                      - configMapRef:
                          name: "{{ config_maps_name }}"
                      - secretRef:
                          name: "{{ secret_name }}"
                restartPolicy: Never
                volumes:
                  - name: "volume-{{ volume_name_logs }}"
                    persistentVolumeClaim:
                      claimName: {{ volume_name_logs }}
