- name: Clear sessions cron job
  kubernetes.core.k8s:
    definition:
      apiVersion: batch/v1
      kind: CronJob
      metadata:
        name: "{{ cron_job_name }}"
        namespace: "{{ openshift_namespace }}"
        labels:
          app: "{{ app_name }}"
      spec:
        schedule: "0 3 * * *"
        concurrencyPolicy: "Forbid"
        jobTemplate:
          spec:
            template:
              metadata:
                labels:
                  app: "{{ app_name }}"
              spec:
                serviceAccountName: builder-for-quay
                containers:
                  - name: "{{ cron_job_name }}"
                    image: "{{ app_image_source }}"
                    command: ["/usr/local/bin/python", "-Wi", "/usr/src/app/infoscience_exports/manage.py", "clearsessions"]
                    volumeMounts:
                    - name: "{{ volume_name_logs }}"
                      mountPath: /var/log/django
                      subPath: infoscience-exports
                    envFrom:
                      - configMapRef:
                          name: "{{ config_maps_name }}"
                      - secretRef:
                          name: "{{ secret_name }}"
                      - secretRef:
                        name: "{{ django_entra_auth_secrets_name }}"
                    resources:
                      requests:
                        memory: "256Mi"
                        cpu: "10m"
                      limits:
                        memory: "2Gi"
                        cpu: "100m"
                restartPolicy: Never
                volumes:
                  - name: "{{ volume_name_logs }}"
                    persistentVolumeClaim:
                      claimName: "{{ volume_name_logs }}"
