- name: PostgreSQL cluster
  kubernetes.core.k8s:
    definition:
      apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      metadata:
        name: "{{ database.cluster }}"
        namespace: "{{ openshift_namespace }}"
        labels:
          app.kubernetes.io/name: "postgresql-cluster"
          app.kubernetes.io/component: database
      spec:
        instances: 2
        monitoring:
          enablePodMonitor: true
        storage:
          size: "{{ database.size }}"
          storageClass: "ocs-storagecluster-ceph-rbd"
        enableSuperuserAccess: true
        resources:
          requests:
            cpu: "1m"
            memory: "256Mi"
          limits:
            memory: "512Mi"
        backup:
          retentionPolicy: "{{ database.backup_retentionPolicy }}"
          barmanObjectStore:
            destinationPath: "s3://{{ database.backup_s3.bucket }}/{{ database.backup_s3.folder }}"
            endpointURL: "https://{{ database.backup_s3.endpoint }}"
            s3Credentials:
              accessKeyId:
                name: s3-credentials
                key: AWS_ACCESS_KEY_ID
              secretAccessKey:
                name: s3-credentials
                key: AWS_SECRET_ACCESS_KEY
        env:
          - name: AWS_REQUEST_CHECKSUM_CALCULATION
            value: WHEN_REQUIRED
          - name: AWS_RESPONSE_CHECKSUM_VALIDATION
            value: WHEN_REQUIRED
        postgresql:
          parameters:
            max_connections: "600"
            max_slot_wal_keep_size: 1GB
            shared_buffers: 128MB
        managed:
          roles:
            - name: "{{ database.user }}"
              ensure: present
              login: true
              superuser: false
              passwordSecret:
                name: "infoscience-exports-db-credentials"

- name: PostgreSQL database
  kubernetes.core.k8s:
    definition:
      apiVersion: postgresql.cnpg.io/v1
      kind: Database
      metadata:
        name: "{{ database.name }}"
        namespace: "{{ openshift_namespace }}"
        labels:
          app.kubernetes.io/name: "postgresql-database"
          app.kubernetes.io/component: database
      spec:
        name: "{{ database.name }}"
        owner: "{{ database.user }}"
        cluster:
          name: "{{ database.cluster }}"

- name: Scheduled DB backup
  kubernetes.core.k8s:
    definition:
      apiVersion: postgresql.cnpg.io/v1
      kind: ScheduledBackup
      metadata:
        name: "{{ database.cluster }}"
        namespace: "{{ openshift_namespace }}"
        labels:
          app.kubernetes.io/name: "infoscience-exports"
          app.kubernetes.io/component: backup
      spec:
        schedule: "{{ database.backup_frequency }}"
        backupOwnerReference: self
        cluster:
          name: "{{ database.cluster }}"
