- name: infoscience-exports deploy
  openshift:
    state: latest
    resource: Deployment
    name: "{{ deploy_name }}"
    namespace: "{{ openshift_namespace }}"
    content: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        annotations:
          version: "{{ image_version }}"
        labels:
          app: "{{ app_name }}"
          author: jdelasoie
          team: idev-fsd
          version: "{{ image_version }}"
        name: "{{ deploy_name }}"
        namespace: "{{ openshift_namespace }}"
      spec:
        replicas: 2
        selector:
          matchLabels:
            app: "{{ app_name }}"
        template:
          metadata:
            labels:
              app: "{{ app_name }}"
              author: jdelasoie
              team: idev-fsd
              deployment: "{{ deploy_name }}"
          spec:
            containers:
              - envFrom:
                - configMapRef:
                    name: "{{ config_maps_name }}"
                - secretRef:
                    name: "{{ secret_name }}"
                image: "{{ openshift_local_images_base }}"
                imagePullPolicy: Always
                name: pod-infoscience-exports
                ports:
                  - containerPort: 3000
                    protocol: TCP
                volumeMounts:
                  - mountPath: /var/log/django
                    name: "volume-{{ volume_name_logs }}"
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            terminationGracePeriodSeconds: 30
            volumes:
              - name: "volume-{{ volume_name_logs }}"
                persistentVolumeClaim:
                  claimName: {{ volume_name_logs }}
