- name: Secrets
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "{{ secret_name }}"
        namespace: "{{ openshift_namespace }}"
        labels:
          app: "{{ app_name }}"
      stringData:
        DATABASE_URL: "{{ lookup('file', database_url_definition_path) }}"
        SECRET_KEY: "{{ lookup('file', secret_key_definition_path) }}"

- name: Entra auth config secrets
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "{{ django_entra_auth_secrets_name  }}"
        namespace: "{{ openshift_namespace }}"
      stringData:
        AUTH_ENTRA_TENANT_ID:
          "{{
            lookup('file', '{{ keybase_secrets_folder }}/AUTH_ENTRA_TENANT_ID')
          }}"
        AUTH_ENTRA_CLIENT_ID:
          "{{
            lookup('file', '{{ keybase_secrets_folder }}/AUTH_ENTRA_CLIENT_ID')
          }}"
        AUTH_ENTRA_SECRET:
          "{{
            lookup('file', '{{ keybase_secrets_folder }}/AUTH_ENTRA_SECRET')
          }}"
