- name: infoscience-exports secrets
  openshift:
    state: latest
    resource: Secret
    name: "{{ secret_name }}"
    namespace: "{{ openshift_namespace }}"
    content: |
      apiVersion: v1
      stringData:
        SECRET_KEY: "{{ lookup('file', '/keybase/team/epfl_idevfsd/infoscience-exports/SECRET_KEY') }}"
        DATABASE_URL: "{{ lookup('file', '/keybase/team/epfl_idevfsd/infoscience-exports/DATABASE_URL') }}"
      kind: Secret
      metadata:
        name: "{{ secret_name }}"
        namespace: "{{ openshift_namespace }}"
      type: Opaque
