- name: Database secrets
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "infoscience-exports-db-credentials"
        namespace: "{{ openshift_namespace }}"
        labels:
          app.kubernetes.io/name: "{{ app_name }}"
          app.kubernetes.io/component: database
          cnpg.io/reload: "true"
      type: kubernetes.io/basic-auth
      stringData:
        username: "{{ database.user }}"
        password: "{{ database.password }}"
        database: "{{ database.name }}"

- name: S3 DB backup credentials secrets
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: s3-credentials
        namespace: "{{ openshift_namespace }}"
        labels:
          app.kubernetes.io/name: "{{ app_name}}"
          app.kubernetes.io/component: backup
      stringData:
        AWS_ACCESS_KEY_ID: "{{ database.backup_s3.access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ database.backup_s3.secret_key }}"

- name: Web-app secrets
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "{{ secret_name }}"
        namespace: "{{ openshift_namespace }}"
        labels:
          app: "{{ app_name }}"
      stringData:
        DATABASE_URL: "postgres://{{ database.user }}:{{ database.password }}@{{ database.host }}:5432/{{ database.name }}"
        SECRET_KEY: "{{ lookup('file', secret_key_definition_path) }}"

- name: Entra auth config secrets
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "{{ django_entra_auth_secrets_name  }}"
        namespace: "{{ openshift_namespace }}"
      stringData: >-
        {{
          lookup('file', keybase_secrets_folder ~ '/entra_auth.yaml')
          | from_yaml
        }}

