all:
  hosts:
    openshift-4-prod:
      ansible_connection: local
      ansible_host: localhost
      ansible_python_interpreter: "{{ exportsible_suitcase_dir }}/bin/python3"
      openshift_namespace: svc0089p-infoscience
  vars:
    # Image building
    python_image_version: "python:3.12-slim"
    python_image_source: "docker.io/python/{{ python_image_version }}"

    # Route
    avi_route_access_level: public

    # App
    ### Image
    app_version: "0.6.0"
    app_image: "infoscience-exports:{{ app_version }}"
    app_image_source: "{{ quay_host }}/{{ quay_organisation_name }}/{{ app_image }}"

    ### Secrets
    database_url_definition_path: "/keybase/team/epfl_idevfsd/infoscience-exports/prod/DATABASE_URL"
    secret_key_definition_path: "/keybase/team/epfl_idevfsd/infoscience-exports/prod/SECRET_KEY"

    ### Config
    django_settings_module: "settings.prod"
    #django_site_url: "infoscience-exports-prod.128.178.211.3.nip.io"
    django_site_url: "infoscience-exports.epfl.ch"
    django_site_full_url: "https://{{ django_site_url }}"
    django_cache_timeout: "43200"
    django_range_display: "500"
    django_server_engine: "dspace"

    ### Security
    tequila_allowed_request_hosts: 10.98.72.206|10.98.72.207|10.98.72.208
