services:
  web:
    build: .
    restart: always
    stdin_open: true
    tty: true
    expose:
      - "80"
    links:
      - postgres
    depends_on:
      - postgres
    env_file:
      - ./env/django.env
    environment:
      # the following vars need to be overridden because the directive env_file
      # does not compute their value from the other variables
      - SITE_URL=${SITE_URL}
      - DATABASE_URL=${DATABASE_URL}
    command: gunicorn --reload -w 4 -b :80 --chdir /usr/src/app/infoscience_exports wsgi:application

  postgres:
    image: postgres:12
    ports:
      - "25432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
