services:
  web:
    build: .
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./infoscience_exports:/usr/src/app/infoscience_exports
      - ./staticfiles:/usr/src/app/staticfiles
      - ./coverage.xml:/usr/src/app/coverage.xml
      - ./docker_volumes/logs:/var/log/django
      - ./entrypoint.sh:/usr/src/app/entrypoint.sh
    env_file:
      # mix the two
      - ./env/django.env
      - .env
    environment:
      # the following vars need to be overridden because the directive env_file
      # does not compute their value from the other variables
      - GUNICORN_CMD_ARGS= --reload
      - SITE_URL=${SITE_URL}
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@db:5432/infoscience_exports
    command: >
      sh -c "python infoscience_exports/manage.py collectstatic --noinput &&
             python infoscience_exports/manage.py migrate &&
             /usr/src/app/entrypoint.sh"

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=infoscience_exports
    ports:
      - "25432:5432"
    volumes:
      - ./docker_volumes/db_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
