[project]
name = "Infoscience-exports app"
revision = "1.0"

[profiles.default]

AUTH_ENTRA_TENANT_ID = { description = "The ID of the tenant the app will auth the users on Entra", required = true }
AUTH_ENTRA_CLIENT_ID = { description = "The ID of the client the app will auth the users on Entra", required = true }
AUTH_ENTRA_SECRET = { description = "The secret that assert the app is allowed to auth on Entra", required = true }
SECRET_KEY = { description = "A secret key for a particular Django installation. This is used to provide cryptographic signing, and should be set to a unique, unpredictable value.", required = true }
