# Generated by Django 2.0.2 on 2018-02-15 14:00

import dirtyfields.dirtyfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bullets_type', models.CharField(choices=[('C', 'Character'), ('N', 'Number')], max_length=1, null=True)),
                ('bullets_text', models.CharField(max_length=5, null=True)),
                ('bullets_order', models.CharField(choices=[('+', 'Ascending'), ('-', 'Descending')], default='+', max_length=1, null=True)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.TextField()),
            ],
            options={
                'ordering': ['-id'],
            },
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin),
        ),
    ]
