# Generated by Django 2.0.2 on 2018-02-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='formats_type',
            field=models.CharField(choices=[('SHORT', 'short'), ('DETAILED', 'detailed'), ('DETAILED_WITH_ABSTRACT', 'detailed')], default='SHORT', max_length=255),
        ),
        migrations.AddField(
            model_name='export',
            name='groupsby_type',
            field=models.CharField(choices=[('YEAR_ASC', 'year ascending'), ('YEAR_DESC', 'year descending'), ('DOC', 'document type')], default='YEAR_DESC', max_length=255),
        ),
        migrations.AddField(
            model_name='export',
            name='include_pending_publications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='export',
            name='show_detailed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='export',
            name='show_fulltext',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='export',
            name='show_linkable_authors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='export',
            name='show_linkable_titles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='export',
            name='show_links_for_printing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='export',
            name='show_viewpublisher',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='export',
            name='use_doc_as_title',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='export',
            name='use_year_as_title',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='export',
            name='bullets_type',
            field=models.CharField(choices=[('NONE', ''), ('CHARACTER_STAR', '*'), ('CHARACTER_MINUS', '-'), ('NUMBER_ASC', '1, 2, 3, ...'), ('NUMBER_DESC', '..., 3, 2, 1')], default='NONE', max_length=255),
        ),
    ]
