# Generated by Django 2.0.2 on 2018-02-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0002_auto_20180222_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='export',
            name='include_pending_publications',
        ),
        migrations.RemoveField(
            model_name='export',
            name='use_doc_as_title',
        ),
        migrations.RemoveField(
            model_name='export',
            name='use_year_as_title',
        ),
        migrations.AddField(
            model_name='export',
            name='groupsby_doc',
            field=models.CharField(choices=[('NONE', ''), ('DOC', 'document type'), ('DOC_TITLE', 'document type, document type as title')], default='NONE', max_length=255),
        ),
        migrations.AddField(
            model_name='export',
            name='groupsby_year',
            field=models.CharField(choices=[('NONE', ''), ('YEAR_DESC', 'year: descending'), ('YEAR_DESC_TITLE', 'year: descending, year as title'), ('YEAR_DESC_PUBL', 'year: descending, with pending publications'), ('YEAR_DESC_TITLE_PUBL', 'year: descending, year as title, with pending publications'), ('YEAR_ASC', 'year: ascending'), ('YEAR_ASC_TITLE', 'year: ascending, year as title'), ('YEAR_ASC_PUBL', 'year: ascending, with pending publications'), ('YEAR_ASC_TITLE_PUBL', 'year: descending, year as title, with pending publications')], default='NONE', max_length=255),
        ),
        migrations.AlterField(
            model_name='export',
            name='formats_type',
            field=models.CharField(choices=[('SHORT', 'short'), ('DETAILED', 'detailed'), ('DETAILED_WITH_ABSTRACT', 'detailed with abstract')], default='SHORT', max_length=255),
        ),
        migrations.AlterField(
            model_name='export',
            name='groupsby_type',
            field=models.CharField(choices=[('YEAR_DESC', 'year: descending'), ('YEAR_DESC_TITLE', 'year: descending, year as title'), ('YEAR_DESC_PUBL', 'year: descending, with pending publications'), ('YEAR_DESC_TITLE_PUBL', 'year: descending, year as title, with pending publications'), ('YEAR_ASC', 'year: ascending'), ('YEAR_ASC_TITLE', 'year: ascending, year as title'), ('YEAR_ASC_PUBL', 'year: ascending, with pending publications'), ('YEAR_ASC_TITLE_PUBL', 'year: descending, year as title, with pending publications'), ('DOC', 'document type'), ('DOC_TITLE', 'document type, document type as title')], default='YEAR_DESC', max_length=255),
        ),
    ]
