# Generated by Django 2.0.2 on 2018-03-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0005_auto_20180302_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='show_pending_publications',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='export',
            name='formats_type',
            field=models.CharField(choices=[('SHORT', 'short'), ('DETAILED', 'detailed')], default='SHORT', max_length=255),
        ),
        migrations.AlterField(
            model_name='export',
            name='groupsby_type',
            field=models.CharField(choices=[('NONE', ''), ('YEAR_TITLE', 'year: year as title'), ('DOC', 'document type'), ('DOC_TITLE', 'document type, document type as title')], default='NONE', max_length=255),
        ),
        migrations.AlterField(
            model_name='export',
            name='groupsby_year',
            field=models.CharField(choices=[('NONE', ''), ('YEAR_TITLE', 'year: year as title')], default='NONE', max_length=255),
        ),
    ]
