# Generated by Django 2.0.2 on 2018-03-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0005_auto_20180302_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='memberof',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sciper',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
