# Generated by Django 2.0.2 on 2018-03-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0008_auto_20180309_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='show_article_volume',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='export',
            name='show_article_volume_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='export',
            name='show_article_volume_pages',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='export',
            name='show_book_chapter_doi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='export',
            name='show_book_chapter_isbn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='export',
            name='show_book_doi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='export',
            name='show_book_isbn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='export',
            name='show_conf_paper_journal_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='export',
            name='show_conf_proceed_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='export',
            name='show_conf_proceed_place',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='export',
            name='show_patent_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='export',
            name='show_report_working_papers_pages',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='export',
            name='show_thesis_directors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='export',
            name='show_thesis_pages',
            field=models.BooleanField(default=False),
        ),
    ]
