# Generated by Django 2.0.3 on 2018-03-21 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0009_auto_20180315_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='export',
            name='show_linkable_titles',
        ),
    ]
