# Generated by Django 2.0.3 on 2018-03-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0010_remove_export_show_linkable_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='groupsby_doc',
            field=models.CharField(choices=[('NONE', ''), ('DOC_TITLE', 'document type as title')], default='NONE', max_length=255),
        ),
        migrations.AlterField(
            model_name='export',
            name='groupsby_type',
            field=models.CharField(choices=[('NONE', ''), ('YEAR_TITLE', 'year as title'), ('DOC_TITLE', 'document type as title')], default='NONE', max_length=255),
        ),
    ]
