# Generated by Django 2.0.3 on 2018-04-05 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0012_export_show_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyExport',
            fields=[
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='exports.Export')),
                ('legacy_url', models.TextField()),
                ('language', models.TextField()),
                ('referenced_url', models.TextField()),
                ('origin', models.TextField(choices=[('OTHER', ''), ('JAHIA', 'Jahia'), ('PEOPLE', 'People')])),
                ('origin_sciper', models.TextField()),
                ('raw_csv_entry', models.TextField()),
            ],
        ),
    ]
