# Generated by Django 2.0.4 on 2018-04-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0014_auto_20180405_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacyexport',
            name='content_delta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
