# Generated by Django 2.0.3 on 2018-04-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0016_auto_20180418_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacyexport',
            name='legacy_id',
            field=models.IntegerField(),
        ),
    ]
