# Generated by Django 2.0.3 on 2018-04-26 02:58

from django.db import migrations, models
import django.db.models.deletion


def remove_existing_legacy_export(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    LegacyExport = apps.get_model('exports', 'LegacyExport')
    for legacy_export in LegacyExport.objects.all():
        legacy_export.export.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0017_legacyexport_legacy_id'),
    ]

    operations = [
        migrations.RunPython(remove_existing_legacy_export),
        migrations.DeleteModel('LegacyExport'),
        migrations.CreateModel(
            name='LegacyExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('export', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='exports.Export')),
                ('legacy_id', models.IntegerField(blank=True, null=True)),
                ('content_delta', models.IntegerField(blank=True, null=True)),
                ('legacy_url', models.TextField()),
                ('language', models.TextField()),
                ('referenced_url', models.TextField()),
                ('origin', models.TextField(
                    choices=[('OTHER', ''), ('JAHIA', 'Jahia'),
                             ('PEOPLE', 'People')])),
                ('origin_sciper', models.TextField()),
                ('raw_csv_entry', models.TextField()),
            ],
        ),
    ]