# Generated by Django 2.0.3 on 2018-04-26 02:58

from django.db import migrations, models
import django.db.models.deletion


def remove_existing_legacy_export(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    LegacyExport = apps.get_model('exports', 'LegacyExport')
    export_to_delete = []
    for legacy_export in LegacyExport.objects.all():
        export_to_delete.append(legacy_export.export)

    for export in export_to_delete:
        export.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0017_legacyexport_legacy_id'),
    ]

    operations = [
        migrations.RunPython(remove_existing_legacy_export),
    ]