# Generated by Django 2.2.28 on 2024-05-14 14:57

from django.db import migrations, models


def set_engine_name_as_invenio(apps, schema_editor):
    exports = apps.get_model("exports", "Export")

    for export in exports.objects.all():
        export.server_engine = 'invenio'
        export.save(update_fields=["server_engine"])


def rev(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0019_auto_20180426_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='last_rendered_page',
            field=models.TextField(default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='export',
            name='last_rendered_page_usage_at',
            field=models.DateTimeField(default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='export',
            name='server_engine',
            field=models.CharField(blank=True, choices=[('invenio', 'invenio'), ('dspace', 'dspace')], max_length=10),
        ),
        migrations.RunPython(set_engine_name_as_invenio, rev),
    ]
