# Generated by Django 4.2.14 on 2024-07-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0021_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='limit',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
