# Generated by Django 4.2.26 on 2026-04-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exports", "0021_alter_user_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="export",
            name="server_engine",
            field=models.CharField(
                blank=True,
                choices=[("dspace", "dspace"), ("invenio", "invenio")],
                max_length=10,
            ),
        ),
    ]
