# Generated by Django 4.2.26 on 2026-04-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exports", "0022_alter_export_server_engine"),
    ]

    operations = [
        migrations.AddField(
            model_name="export",
            name="last_rendered_page_generation_duration",
            field=models.DecimalField(
                decimal_places=4, default=None, editable=False, max_digits=7, null=True
            ),
        ),
    ]
