all:
  hosts:
    openshift-4-test:
      ansible_connection: local
      ansible_host: localhost
      ansible_python_interpreter: "{{ exportsible_suitcase_dir }}/bin/python3"
      openshift_namespace: svc0089t-infoscience
  vars:
    # Secrets
    keybase_secrets_folder: "/keybase/team/epfl_idevfsd/infoscience-exports/test"

    # Image building
    ## base
    python_image_version: "python:3.12-slim"
    python_image_source: "{{ quay_repo }}/{{ python_image_version }}"
    ## app
    app_build_image_git_branch: "main"
    app_built_image_tag: "test"

    # Route
    avi_route_access_level: private

    # App
    ### Image
    app_version: "test"
    app_image: "infoscience-exports:{{ app_version }}"
    app_image_source: "{{ quay_host }}/{{ quay_organisation_name }}/{{ app_image }}"

    ### Secrets
    database_url_definition_path: "{{ keybase_secrets_folder }}/DATABASE_URL"
    secret_key_definition_path: "{{ keybase_secrets_folder }}/SECRET_KEY"

    ### Config
    django_settings_module: "settings.prod"
    django_site_url: "infoscience-exports-test.10.98.42.205.nip.io"
    django_site_full_url: "https://{{ django_site_url }}"
    django_cache_timeout: "43200"
    django_range_display: "500"
    django_server_engine: "dspace"

    ### Security
    tequila_allowed_request_hosts: 10.98.82.179|10.98.82.180|10.98.82.181
