- name: Secrets
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "{{ secret_name }}"
        namespace: "{{ openshift_namespace }}"
      stringData:
        DATABASE_URL: "{{ lookup('file', database_url_definition_path) }}"
        SECRET_KEY: "{{ lookup('file', secret_key_definition_path) }}"
