---
# vars file for epfl.infoscience-exports
app_name: "infoscience-exports"
svc_name: "{{ app_name }}"
route_name: "{{ app_name }}"
cron_job_name: "{{ app_name }}-clear-sessions"
secret_name: "infoscience-exports.secrets"
config_maps_name: "infoscience-exports-config"
cname: "infoscience-exports.epfl.ch"
deploy_name: "{{ app_name }}"
openshift_image_registry: "os-docker-registry.epfl.ch"
image_version: "latest"
image_tag: "{{openshift_image_registry}}/{{openshift_namespace}}/{{svc_name}}:{{image_version}}"
openshift_local_images_base: "docker-registry.default.svc:5000/{{ svc_name }}/{{ app_name }}:{{image_version}}"
volume_name_logs: "{{ app_name }}-logs"
volume_name_staticfiles: "{{ app_name }}-staticfiles"

quay_host: "quay-its.epfl.ch"
quay_organisation_name: svc0089

_quay_push_pull_credential: "{{ lookup('file', '/keybase/team/epfl_idevfsd/infoscience-exports/QUAY_BOT_ACCOUNT') }}"

quay_push_pull_config:
  auths:
    "quay-its.epfl.ch":
      "auth": "{{ _quay_push_pull_credential | b64encode }}"
